[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "https://alcatech-webdesign.netlify.app/*"
  to = "https://alcatechwebdesign.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/create-checkout"
  to = "/.netlify/functions/create-checkout"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://152.70.42.81:80/api/:splat"
  status = 200
  force = true
